### ISSUE TITLE
can't updated config object dynamically

### ISSUE THREAD

**Issue by nipunupekshana** [BrockReece/vue-kanban#69]
```
 <kanban-board
      class="kanban-board"
      :stages="leadStatusColumns"
      :blocks="blocksClone"
      :config="config"
      @update-block="updateBlock"
    >
```
im using config object which inside the data in vue.

```
data() {
    return {
      config: {
        accepts() {
          return true;
        }
      }
}
}
```

& im trying to update config object before component render by calling

beforeMount() {
    this.updateConfig();
  },

her is my update function for config :

updateConfig() {
      let New = this.leadStatusLabels.New;
      let Qualified = this.leadStatusLabels.Qualified;
      let OnHold = this.leadStatusLabels.OnHold;
      let Lodged = this.leadStatusLabels.Lodged;
      let Approved = this.leadStatusLabels.Approved;
      let Unsuccessful = this.leadStatusLabels.Unsuccessful;
      let config = {
        accepts(block, target, source) {
          let decision = false;
          if (source.dataset.status === New) {
            if (
              target.dataset.status === Qualified ||
              target.dataset.status === OnHold ||
              target.dataset.status === Unsuccessful
            ) {
              decision = true;
            }
          } else if (source.dataset.status === Qualified) {
            if (
              target.dataset.status === OnHold ||
              target.dataset.status === Lodged ||
              target.dataset.status === Unsuccessful
            ) {
              decision = true;
            }
          } else if (source.dataset.status === OnHold) {
            if (
              target.dataset.status === New ||
              target.dataset.status === Qualified ||
              target.dataset.status === Lodged ||
              target.dataset.status === Approved ||
              target.dataset.status === Unsuccessful
            ) {
              decision = true;
            }
          } else if (source.dataset.status === Lodged) {
            if (
              target.dataset.status === OnHold ||
              target.dataset.status === Approved ||
              target.dataset.status === Unsuccessful
            ) {
              decision = true;
            }
          } else if (source.dataset.status === Approved) {
            if (target.dataset.status === OnHold) {
              decision = true;
            }
          } else if (source.dataset.status === Unsuccessful) {
            if (target.dataset.status === Qualified) {
              decision = true;
            }
          }
          return decision;
        }
      };
      console.log(`updated config `, config);
      this.config = config;
    }

issue is i can't move my cards acording to above conditions. any support to update those config file dynamically?

**Comment by BrockReece** [comment]
Hi, this component uses [Dragula](https://github.com/bevacqua/dragula) under the hood and I don't think it supports dynamic config. I may have misunderstood the code above though but it looks fairly static, is there a reason you are trying to reassign `config`?

I am guessing this is caused by the order of the parent and child lifecycle hooks though. The `beforeMount` hook of this parent component must be called after the `mounted` method of the Kanban component. I have actually written an [article](https://medium.com/@brockreece/vue-parent-and-child-lifecycle-hooks-5d6236bd561f) on how this behaviour may be counterintuitive.

If I was you, I would first try moving this logic into the `created` hook if possible. If not, you could add a `v-if` to the Kanban component so it doesn't mount until after the `beforeMount` hook?

```html
<kanban-board
      v-if="configLoaded" 
      class="kanban-board"
      :stages="leadStatusColumns"
      :blocks="blocksClone"
      :config="config"
      @update-block="updateBlock"
    >
```

I hope that helps?

**Comment by nipunupekshana** [comment]
yah Thanks BrockReece , which works for me :)
